import "server-only";
import { del, put } from "@vercel/blob";

/**
 * Where gallery photos physically live.
 *
 * Deliberately the only file that knows the storage vendor. The gallery
 * actions call `storePhoto`/`removePhoto` and never import @vercel/blob, so
 * moving to Supabase Storage or anywhere else means rewriting this file and
 * nothing else.
 */

/** Set automatically by Vercel once a Blob store is attached to the project. */
const TOKEN_ENV = "BLOB_READ_WRITE_TOKEN";

export class StorageNotConfiguredError extends Error {
  constructor() {
    super(
      `Photo storage is not set up yet. Create a Blob store in the Vercel dashboard ` +
        `and redeploy — that sets ${TOKEN_ENV} for you. Everything else about the ` +
        `gallery works without it; only uploading needs it.`,
    );
    this.name = "StorageNotConfiguredError";
  }
}

/** True when uploads can actually be accepted. */
export function isStorageConfigured(): boolean {
  return Boolean(process.env[TOKEN_ENV]);
}

export interface StoredPhoto {
  url: string;
  key: string;
}

/**
 * Uploads one image and returns where it landed.
 *
 * `addRandomSuffix: false` because the key is already unique and generated by
 * us — letting the store append its own suffix would mean the key we record
 * is not the key we could later delete.
 */
export async function storePhoto(key: string, file: Blob | ArrayBuffer): Promise<StoredPhoto> {
  if (!isStorageConfigured()) throw new StorageNotConfiguredError();

  const result = await put(key, file, {
    access: "public",
    addRandomSuffix: false,
    // Photos are immutable once uploaded: a new picture gets a new key, so
    // these can be cached hard.
    cacheControlMaxAge: 31_536_000,
  });

  return { url: result.url, key: result.pathname };
}

/**
 * Deletes a stored photo, tolerating one that has already gone.
 *
 * Called while removing a database row. A failure here must not abort that:
 * an orphaned file wastes a little space, but a row pointing at a deleted
 * image shows the visitor a broken picture, which is worse.
 */
export async function removePhoto(key: string): Promise<{ ok: boolean; error?: string }> {
  if (!key) return { ok: true };
  if (!isStorageConfigured()) return { ok: false, error: "storage not configured" };

  try {
    await del(key);
    return { ok: true };
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : String(error) };
  }
}
