import "server-only";
import { del, getDownloadUrl, put } from "@vercel/blob";

/**
 * Where gallery photos physically live.
 *
 * Deliberately the only file that knows the storage vendor. The gallery
 * actions call `storePhoto`/`removePhoto` and never import @vercel/blob, so
 * moving to Supabase Storage or anywhere else means rewriting this file and
 * nothing else.
 */

/** Set automatically by Vercel once a Blob store is attached to the project. */
const TOKEN_ENV = "BLOB_READ_WRITE_TOKEN";

export class StorageNotConfiguredError extends Error {
  constructor() {
    super(
      `Photo storage is not reachable: this deployment cannot see ${TOKEN_ENV}. ` +
        `If you have just created the Blob store, redeploy — Vercel captures ` +
        `environment variables when a deployment is built, so a store created ` +
        `afterwards is invisible to the deployment already running.`,
    );
    this.name = "StorageNotConfiguredError";
  }
}

/**
 * Whether this deployment can see a storage token.
 *
 * Advisory only, and deliberately never used to refuse an upload. The usual
 * reason it reads false is that the Blob store was created after the running
 * deployment was built — Vercel captures environment variables at build time,
 * so the store exists but this process cannot see it until a redeploy. That
 * is a true negative and the notice explains it.
 *
 * But a check like this can also be wrong, and when it is, gating on it leaves
 * an admin with no way to proceed and no error to act on. So callers use it to
 * explain, and let the upload attempt produce the real answer.
 */
export function isStorageConfigured(): boolean {
  return Boolean(process.env.BLOB_READ_WRITE_TOKEN);
}

export interface StoredPhoto {
  url: string;
  key: string;
}

/**
 * A URL that saves the file instead of opening it.
 *
 * The `download` attribute on a link is ignored when the file is on another
 * origin, which blob storage always is — so a plain link would just navigate
 * to the image and leave the visitor to save it by hand. This asks the store
 * to send `Content-Disposition: attachment` instead, which browsers honour
 * cross-origin, and the bytes still come straight from the CDN rather than
 * through this app.
 *
 * The saved filename comes from the key, which is why keys are given readable
 * names at upload rather than random ones.
 *
 * Derived rather than stored, so photos uploaded before this existed get the
 * behaviour too. A malformed URL returns unchanged: a link that opens the
 * image is a far better failure than one that goes nowhere.
 */
export function downloadUrlFor(url: string): string {
  try {
    return getDownloadUrl(url);
  } catch {
    return url;
  }
}

/**
 * Uploads one image and returns where it landed.
 *
 * `addRandomSuffix: false` because the key is already unique and generated by
 * us — letting the store append its own suffix would mean the key we record
 * is not the key we could later delete.
 *
 * `contentType` is required rather than optional. Omitted, the SDK sends no
 * type header at all and the store infers one from the key's extension — which,
 * while that extension was copied from the uploaded filename, handed a public
 * form the power to decide how its own file would later be served. Every caller
 * now passes the type the file's bytes were verified to be, so nothing about
 * the eventual response is derived from something the uploader wrote.
 */
export async function storePhoto(
  key: string,
  file: Blob | ArrayBuffer,
  contentType: string,
): Promise<StoredPhoto> {
  const result = await put(key, file, {
    access: "public",
    addRandomSuffix: false,
    contentType,
    // Photos are immutable once uploaded: a new picture gets a new key, so
    // these can be cached hard.
    cacheControlMaxAge: 31_536_000,
  }).catch((error: unknown) => {
    // The SDK's own "no token" failure is opaque. Translate it into the one
    // instruction that actually fixes it, and let anything else through
    // untouched so a real storage fault is not disguised as a setup problem.
    const message = error instanceof Error ? error.message : String(error);
    if (/token/i.test(message) && !isStorageConfigured()) throw new StorageNotConfiguredError();
    throw error;
  });

  return { url: result.url, key: result.pathname };
}

/**
 * Deletes a stored photo, tolerating one that has already gone.
 *
 * Called while removing a database row. A failure here must not abort that:
 * an orphaned file wastes a little space, but a row pointing at a deleted
 * image shows the visitor a broken picture, which is worse.
 */
export async function removePhoto(key: string): Promise<{ ok: boolean; error?: string }> {
  if (!key) return { ok: true };

  // Attempted regardless of what the advisory check thinks: if the token is
  // there, the file should go, and refusing on a bad guess would leave files
  // behind with nothing pointing at them.
  try {
    await del(key);
    return { ok: true };
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : String(error) };
  }
}
