// Jordanian universities offered in the register form's university dropdown,
// sourced from the official 2026 Maze Solver Robot Competition application form.
export const UNIVERSITIES = [
  "Ajloun National University",
  "Al al-Bayt University (AABU)",
  "Al-Ahliyya Amman University",
  "Al-Balqa' Applied University (BAU)",
  "Al-Hussein Bin Talal University (AHU)",
  "Al-Hussein Technical University (HTU)",
  "Isra University",
  "Al-Zaytoonah University of Jordan",
  "American University of Madaba (AUM)",
  "Amman Arab University (AAU)",
  "Applied Science Private University (ASU)",
  "Aqaba University of Technology (AUT)",
  "German Jordanian University (GJU)",
  "Irbid National University",
  "Jadara University",
  "Jerash University",
  "Jordan University of Science and Technology (JUST)",
  "Luminus Technical University College (LTUC)",
  "Middle East University (MEU)",
  "Mutah University",
  "Philadelphia University",
  "Princess Sumaya University for Technology (PSUT)",
  "Tafila Technical University (TTU)",
  "The Hashemite University (HU)",
  "The University of Jordan (UJ)",
  "University of Petra (UOP)",
  "The World Islamic Sciences and Education University (WISE)",
  "Yarmouk University (YU)",
  "Zarqa University",
  "Other",
] as const;

export type University = (typeof UNIVERSITIES)[number];
