import { ImageResponse } from "next/og";
import { generateMaze } from "@/lib/maze";
import { DIAGRAM_BRAID, RULES } from "@/lib/rules";

/**
 * The card that appears when the site is shared.
 *
 * There was none, so every link posted to WhatsApp, Discord or LinkedIn
 * rendered as a bare URL. Placed at the app root, so it covers every page that
 * does not declare its own.
 *
 * The maze is generated by the same engine the competition uses rather than
 * being a drawn asset — the picture is the actual thing, and it costs nothing
 * to keep in step if the generator ever changes.
 */

/*
  Edge, not Node.

  Under the Node runtime @vercel/og resolves its bundled default font through
  `fileURLToPath`, which throws `TypeError: Invalid URL` during `next build` and
  fails the whole export. The edge build loads the same font differently and
  does not. Nothing here needs a Node API — the maze generator is pure — so the
  edge runtime costs nothing.
*/
export const runtime = "edge";

export const alt = "MMRC 26 — the IEEE RAS HTU Micro Mouse Robot Competition";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * Seeded rather than random.
 *
 * The image is generated once and then cached at the edge, so randomness would
 * not produce variety — it would only make the one card that does get built
 * unreproducible, and a bad draw would be stuck there until the next deploy.
 */
function seededRandom(seed: number): () => number {
  let t = seed >>> 0;
  return () => {
    t += 0x6d2b79f5;
    let r = t;
    r = Math.imul(r ^ (r >>> 15), r | 1);
    r ^= r + Math.imul(r ^ (r >>> 7), r | 61);
    return ((r ^ (r >>> 14)) >>> 0) / 4294967296;
  };
}

export default async function Image() {
  // Braided, like the diagrams on the rules page: a perfect carve reads as
  // long empty corridors at this scale, where a few loops read as a maze.
  const maze = generateMaze(RULES.mazeGrid, seededRandom(20260821), DIAGRAM_BRAID);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          background: "linear-gradient(135deg, #2a0e2f 0%, #5F2167 55%, #862633 140%)",
          color: "#ffffff",
          padding: 64,
        }}
      >
        <div style={{ display: "flex", flexDirection: "column", flex: 1 }}>
          <div
            style={{
              fontSize: 26,
              letterSpacing: 6,
              textTransform: "uppercase",
              color: "#F2A900",
            }}
          >
            IEEE RAS HTU Student Chapter
          </div>
          <div style={{ fontSize: 132, fontWeight: 800, lineHeight: 1.05, marginTop: 12 }}>
            MMRC 26
          </div>
          <div style={{ fontSize: 36, marginTop: 16, color: "rgba(255,255,255,0.88)" }}>
            Micro Mouse Robot Competition
          </div>
          <div style={{ fontSize: 26, marginTop: 28, color: "rgba(255,255,255,0.65)" }}>
            Build a maze-solving robot. Race the clock.
          </div>
        </div>

        {/* The maze itself, drawn from the generator's own wall geometry. */}
        <svg width={420} height={420} viewBox={maze.viewBox} style={{ marginLeft: 48 }}>
          <rect
            x={0}
            y={0}
            width={maze.size * 20}
            height={maze.size * 20}
            fill="rgba(0,0,0,0.22)"
            rx={12}
          />
          <rect
            x={maze.goal.x}
            y={maze.goal.y}
            width={maze.goal.size}
            height={maze.goal.size}
            fill="#F2A900"
            opacity={0.85}
          />
          {maze.walls.map((d, i) => (
            <path key={i} d={d} stroke="rgba(255,255,255,0.82)" strokeWidth={2.4} fill="none" />
          ))}
          <path
            d={maze.routes[0]!.solution}
            stroke="#F2A900"
            strokeWidth={5}
            fill="none"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      </div>
    ),
    size,
  );
}
