import { NextResponse } from "next/server";
import { requireAdminApi } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

/**
 * An admin's view of one team's proof-of-payment screenshot.
 *
 * The file itself lives in Vercel Blob, which only offers public objects — the
 * SDK has no private mode. Its key is unguessable, but "unguessable" and
 * "private" are not the same thing: the moment a blob URL is rendered as an
 * href it enters browser history, and from there it can be copied, synced, or
 * handed on, and it keeps working forever because the object is cached for a
 * year. A bank confirmation carries an account name, a phone number and often a
 * balance, so that is not an acceptable resting place for it.
 *
 * So the URL is never sent to a browser at all. It stays in the database and in
 * this handler's own fetch, and the bytes reach the admin through a request
 * that had to present a valid session first. That does not make the object
 * store private, and it is not claimed to — it removes the routes by which the
 * URL would otherwise escape.
 *
 * A route handler rather than a page because it returns an image, and because
 * it must answer an unauthenticated caller with a status rather than the
 * redirect `requireAdmin()` would issue.
 */

// Reads one registration row and proxies a remote object; nothing here is
// cacheable, and caching it is the specific thing this route exists to prevent.
export const dynamic = "force-dynamic";

export async function GET(_request: Request, { params }: { params: { id: string } }) {
  const admin = await requireAdminApi();
  if (!admin) {
    return new NextResponse("Not found", { status: 404 });
  }

  const registration = await prisma.registration.findUnique({
    where: { id: params.id },
    select: { paymentScreenshotUrl: true, paymentScreenshotKey: true },
  });

  // One response for "no such registration" and for "that registration has no
  // screenshot", so this cannot be used to test which ids exist.
  if (!registration?.paymentScreenshotUrl) {
    return new NextResponse("Not found", { status: 404 });
  }

  let upstream: Response;
  try {
    upstream = await fetch(registration.paymentScreenshotUrl, { cache: "no-store" });
  } catch {
    return new NextResponse("The screenshot could not be retrieved from storage.", { status: 502 });
  }

  if (!upstream.ok || !upstream.body) {
    return new NextResponse("The screenshot could not be retrieved from storage.", { status: 502 });
  }

  // The stored key is generated by us and already stripped of anything unsafe
  // (see paymentScreenshotKey); the last segment is the filename an admin sees
  // in their downloads folder.
  const filename = registration.paymentScreenshotKey?.split("/").pop() || "payment-screenshot";

  return new NextResponse(upstream.body, {
    headers: {
      "Content-Type": upstream.headers.get("content-type") ?? "application/octet-stream",
      // Kept out of every cache between here and the admin's screen. The whole
      // point is that this content does not persist anywhere it can be reached
      // without a session.
      "Cache-Control": "private, no-store, max-age=0",
      "Content-Disposition": `attachment; filename="${filename}"`,
      // Belt and braces: the bytes are attacker-supplied in the sense that a
      // registrant chose them, so refuse to let a browser sniff them into
      // something executable.
      "X-Content-Type-Options": "nosniff",
    },
  });
}
